config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { omniauth_callbacks: 'callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  match '/users/new' => 'users#new', via: [:get, :post], :as => 'new_user'
  post '/users/create' => 'users#create', :as => 'create_user'

  get '/users/auth/odnoklassniki/callback' => 'callbacks#odnoklassniki'

  devise_for :admins

  root 'front#index'
  get '/rules' => 'front#rules', :as => 'rules'
  get '/about' => 'front#about', :as => 'about'
  get '/winners' => 'front#winners', :as => 'winners'
  resources :photos, :only => [:create, :new, :show]
  resources :uploads, :only => [:create]
  get '/user/:id' => 'front#user', :as => 'user'
  get '/map(/:alias)' => 'front#map', :as => 'map'

  post '/api/check_email' => 'api#check_email'
  post '/api/create_user' => 'api#create_user'
  post '/api/login_user' => 'api#login_user'
  post '/api/get_points' => 'api#get_points'
  post '/api/get_points_paged' => 'api#get_points_paged'
  post '/api/get_user_points' => 'api#get_user_points'
  post '/api/get_point' => 'api#get_point'
  post '/api/upvote' => 'api#upvote'
  post '/api/load_more_winners' => 'api#load_more_winners'
  post '/api/feedback' => 'api#feedback'

  %w( 404 422 500 ).each do |code|
    get code, :to => 'errors#show', :code => code
  end

  namespace :admin do
    resources :maps, :only => ['index', 'destroy'] do
      post 'make_primary', on: :member
      post 'unmake_primary', on: :member
      post 'recreate', on: :collection
    end
    resources :users, :only => ['index', 'destroy', 'show']
    resources :photos, :only => ['index', 'destroy', 'show'] do
      post 'make_tile', on: :member
      post 'unmake_tile', on: :member
      post 'publish', on: :member
      post 'unpublish', on: :member
      post 'cancel', on: :member
      get 'unpublished', on: :collection
      get 'cancelled', on: :collection
    end
    resources :regions, :only => ['index', 'show'] do
      resources :generics, :only => ['show', 'create', 'new', 'destroy']
      resources :photos, :only => ['index', 'show', 'destroy'], :controller => 'region_photos' do
        post 'make_tile', on: :member
        post 'unmake_tile', on: :member
        post 'publish', on: :member
        post 'unpublish', on: :member
        post 'cancel', on: :member
      end
    end
    resources :feedbacks, :only => ['index', 'show', 'destroy']
    resources :winners, only: ['index', 'new', 'create']
    resources :prizes, only: ['index', 'new', 'create']
    get "/search" => "dashboard#search"
    get "/" => "dashboard#index"
  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base

  belongs_to :user
  belongs_to :region
  belongs_to :week

  has_one :winner

  acts_as_mappable

  paginates_per 16

  mount_uploader :image, ImageUploader
  mount_uploader :tile, TileUploader

  scope :published, -> { where(is_approved: true).where(is_cancelled: false) }

  # Photo.user_last_day(current_user)
  scope :user_last_day, lambda { |user|
    where(:user_id => user.id).where("created_at >= ?", Time.zone.now.beginning_of_day)
  }

  acts_as_votable

  after_create :check_tile

  def check_tile
    Photo.createTile(self)
  end

  def self.createTile(photo)
    photo.tile = File.open(File.join(Rails.root, "data/x.png"))
    photo.save
  end

  def self.createMap
    tiles = []
    error = false
    Region.all.each do |region|
      if Photo.where(:region_id => region.id).where(:is_tile => true).exists?
        tiles.push(Photo.includes(:region).where(:region_id => region.id).where(:is_tile => true).first)
      else
        if Generic.where(:region_id => region.id).exists?
          tiles.push(Generic.where(:region_id => region.id).order('RAND()').first)
        else
          error = true
        end
      end
    end

    if !error

      canvas = ::Magick::Image.read(File.join(Rails.root, "data/canvas.png")).first
      borders = ::Magick::Image.read(File.join(Rails.root, "data/borders.png")).first
      tiles.each do |tile|
        if !tile.nil?
          overlay = ::Magick::Image.read(File.join(Rails.root, "public"+tile.tile_url)).first
          canvas.composite!(overlay, tile.region.tile_left, tile.region.tile_top, Magick::OverCompositeOp)
        end
      end
      canvas.composite!(borders, 0, 0, Magick::OverCompositeOp)

      if File.exists?(File.join(Rails.root, "tmp/m.png"))
        File.delete(File.join(Rails.root, "tmp/m.png"))
      end
      canvas.write(File.join(Rails.root, "tmp/m.png"))

      map = Map.create()
      map.image = File.open(File.join(Rails.root, "tmp/m.png"))
      map.save
    end
  end

  def self.makeFolders
    require 'fileutils'
    Region.all.each do |region|
      x = File.join(Rails.root, "data/photos/", region.alias)
      FileUtils::mkdir_p x
      # Dir.mkdir(File.join(Rails.root, "data/photos/", region.alias))
    end
  end

end

app/controllers/admin/photos_controller.rb
class Admin::PhotosController < ApplicationController

  before_action :authenticate_admin!

  layout "admin"

  def index
    @photos = Photo.order('created_at DESC').page params[:page]
  end

  def show
    @photo = Photo.includes([:user, :region]).where(:id => params[:id]).first
  end

  def publish
    @photo = Photo.includes(:user).find(params[:id])
    @photo.is_approved = true
    @photo.save
    UserMailer.approved_email(@photo).deliver_now
    flash[:notice] = 'Фото опубликовано'
    redirect_to :back
  end

  def cancel
    @photo = Photo.includes(:user).find(params[:id])
    @photo.is_cancelled = true
    @photo.save
    UserMailer.cancelled_email(@photo).deliver_now
    flash[:notice] = 'Фото отменено'
    redirect_to :back
  end

  def unpublish
    @photo = Photo.find(params[:id])
    @photo.is_approved = false
    @photo.save
    flash[:notice] = 'Фото снято с публикации'
    redirect_to :back
  end

  def make_tile
    @photo = Photo.find(params[:id])
    @photo.is_tile = true
    @photo.save
    flash[:notice] = 'Фото сделано тайлом для своего региона'
    redirect_to :back
  end

  def unmake_tile
    @photo = Photo.find(params[:id])
    @photo.is_tile = false
    @photo.save
    flash[:notice] = 'Фото убрано из тайлов'
    redirect_to :back
  end

  def unpublished
    @photos = Photo.where(:is_approved => false).where(:is_cancelled => false).order('created_at DESC').page params[:page]
  end

  def cancelled
    @photos = Photo.where(:is_cancelled => true).order('created_at DESC').page params[:page]
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  before_filter :ensure_signup_complete, only: [:create, :new]
  before_filter :redirect_to_root, only: [:new, :create]

  def show
    @photo = Photo.includes([:region, :user]).find(params[:id])
    if user_signed_in?
      if current_user.voted_for? @photo
        @can_vote = false
      else
        @can_vote = true
      end
    else
      @can_vote = false
    end
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    @photo.user_id = current_user.id

    region_title = params[:photo][:region_name]
    if region_title == 'Центральный федеральный округ'
      region_title = 'Московская область'
    end
    if region_title == 'Северо-Западный федеральный округ'
      region_title = 'Ленинградская область'
    end
    if region_title == 'Севастополь'
      region_title = 'Республика Крым'
    end

    region = Region.where('title like ?',region_title).first
    @photo.region_id = region.id
    @photo.week_id = Week.current.id
    @photo.image = File.open(File.join(Rails.root, "public/"+params[:photo][:image_url]))
    if @photo.save
      UserMailer.uploaded_email(@photo).deliver_now
    end
  end

  private

  def photo_params
    params.require(:photo).permit([:title, :lat, :lng])
  end

  def redirect_to_root
    redirect_to root_path
  end

end

app/helpers/admin/photos_helper.rb
module Admin::PhotosHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/admin/photos/cancelled.html.haml
- content_for :header do

  .breadcrumbs
    Отмененные фото

.table-container


  %table.table
    %thead
      %tr
        %th(style="width: 30px")
        %th
          Название
        %th(style="width: 100px; text-align: center") Пользователь
        %th(style="width: 100px; text-align: center") Регион

    - @photos.each do |photo|
      %tr.cancelled
        %td
          .image-tiny
            = link_to photo.image_url(:main), :class => 'fancybox' do
              = image_tag photo.image_url(:tiny)
        %td
          = link_to admin_photo_path(photo.id) do
            = photo.title
        %td(style="text-align:left")
          = link_to (photo.user.first_name + '&nbsp;' + photo.user.last_name).html_safe, admin_user_path(photo.user.id)
        %td(style="text-align:left")
          = link_to photo.region.title, admin_region_path(photo.region.id)

  .pages-container
    = paginate @photos

app/views/admin/photos/index.html.haml
- content_for :header do

  .breadcrumbs
    Фотографии

.table-container


  %table.table
    %thead
      %tr
        %th(style="width: 30px")
        %th
          Название
        %th(style="width: 100px; text-align: center") Пользователь
        %th(style="width: 100px; text-align: left") Регион
        %th(style="width: 200px; text-align: right") Дата создания

    - @photos.each do |photo|
      - if photo.is_approved
        %tr
          %td
            .image-tiny
              = link_to photo.image_url(:main), :class => 'fancybox' do
                = image_tag photo.image_url(:tiny)
          %td
            = link_to admin_photo_path(photo.id, page: params[:page]) do
              = photo.title
          %td(style="text-align:left")
            = link_to (photo.user.first_name + '&nbsp;' + photo.user.last_name).html_safe, admin_user_path(photo.user.id)
          %td(style="text-align:left")
            = link_to photo.region.title, admin_region_path(photo.region.id)
          %td(style="text-align:right")
            = link_to photo.created_at.strftime("%Y-%m-%d")

      - else
        %tr.unapproved
          %td
            .image-tiny
              = image_tag photo.image_url(:tiny)
          %td
            = link_to admin_photo_path(photo.id, page: params[:page]) do
              = photo.title
          %td(style="text-align:left")
            = link_to (photo.user.first_name + '&nbsp;' + photo.user.last_name).html_safe, admin_user_path(photo.user.id)
          %td(style="text-align:right")
            = link_to photo.region.title, admin_region_path(photo.region.id)

  .pages-container
    = paginate @photos

app/views/admin/photos/show.html.haml
- content_for :header do

  .pull-right
    = link_to admin_photos_path(page: params[:page]), :class => 'button button-hollow button-round button-small preview-website' do
      Вернуться к списку

  .breadcrumbs
    = @photo.title

.table-container

  %table.table.user-table
    %tr
      %th(style="text-align:right; width: 200px") Заголовок
      %td= @photo.title
    %tr
      %th(style="text-align:right; width: 200px") Автор
      %td= "#{@photo.user.name} | #{@photo.user.email}"

    %tr
      %th(style="text-align:right; width: 200px") Регион
      %td= @photo.region.title
    %tr
      %th(style="text-align:right; width: 200px") Положение
      %td
        = @photo.lat.to_s + ';' + @photo.lng.to_s
    %tr
      %th(style="text-align:right; width: 200px") Голосов
      %td
        = @photo.votes_for.size

.container
  .tile-help
    %p
      - if @photo.is_approved
        = link_to "Снять с публикации", unpublish_admin_photo_path(@photo.id), :method => :post, :class => 'button button-primary'
      - else
        = link_to "Опубликовать", publish_admin_photo_path(@photo.id), :method => :post, :class => 'button button-primary'


.table-container

  .image-mapper
    .image
      = image_tag @photo.image_url(:main)
    .mapper
      .mapbox#mapbox(style="height: 360px")
      = image_tag @photo.tile_url, :class => 'tile'


:javascript
  ymaps.ready(init);

  function init () {
    var myMap = new ymaps.Map("mapbox", {
      center: [#{@photo.lat}, #{@photo.lng}],
      zoom: #{@photo.zoom},
      controls: ['smallMapDefaultSet']
    });

    var myPlacemark = new ymaps.Placemark([#{@photo.lat}, #{@photo.lng}], {}, {
      iconLayout: "default#image",
      iconImageHref: "#{@photo.image_url(:marker)}",
      iconImageSize: [40, 45],
      iconImageOffset: [-20, -45]
    });

    myMap.geoObjects.add(myPlacemark);

  }

app/views/admin/photos/unpublished.html.haml
- content_for :header do

  .breadcrumbs
    Неопубликованные фотографии

.table-container


  %table.table
    %thead
      %tr
        %th(style="width: 30px")
        %th
          Название
        %th(style="width: 100px; text-align: center") Пользователь
        %th(style="width: 100px; text-align: center") Регион
        %th(style="width: 100px; text-align: right")
        %th(style="width: 100px; text-align: right")

    - @photos.each do |photo|
      %tr.unapproved
        %td
          .image-tiny
            = link_to photo.image_url(:main), :class => 'fancybox' do
              = image_tag photo.image_url(:tiny)
        %td
          = link_to admin_photo_path(photo.id) do
            = photo.title
        %td(style="text-align:left")
          = link_to (photo.user.first_name + '&nbsp;' + photo.user.last_name).html_safe, admin_user_path(photo.user.id)
        %td(style="text-align:left")
          = link_to photo.region.title, admin_region_path(photo.region.id)
        %td(style="text-align:right")
          = link_to "Опубликовать", publish_admin_photo_path(photo.id), :method => :post, :class => 'button button-primary'
        %td(style="text-align:right")
          = link_to "Отменить", cancel_admin_photo_path(photo.id), :method => :post, :class => 'button button-danger'

  .pages-container
    = paginate @photos