config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { omniauth_callbacks: 'callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  match '/users/new' => 'users#new', via: [:get, :post], :as => 'new_user'
  post '/users/create' => 'users#create', :as => 'create_user'

  get '/users/auth/odnoklassniki/callback' => 'callbacks#odnoklassniki'

  devise_for :admins

  root 'front#index'
  get '/rules' => 'front#rules', :as => 'rules'
  get '/about' => 'front#about', :as => 'about'
  get '/winners' => 'front#winners', :as => 'winners'
  resources :photos, :only => [:create, :new, :show]
  resources :uploads, :only => [:create]
  get '/user/:id' => 'front#user', :as => 'user'
  get '/map(/:alias)' => 'front#map', :as => 'map'

  post '/api/check_email' => 'api#check_email'
  post '/api/create_user' => 'api#create_user'
  post '/api/login_user' => 'api#login_user'
  post '/api/get_points' => 'api#get_points'
  post '/api/get_points_paged' => 'api#get_points_paged'
  post '/api/get_user_points' => 'api#get_user_points'
  post '/api/get_point' => 'api#get_point'
  post '/api/upvote' => 'api#upvote'
  post '/api/load_more_winners' => 'api#load_more_winners'
  post '/api/feedback' => 'api#feedback'

  %w( 404 422 500 ).each do |code|
    get code, :to => 'errors#show', :code => code
  end

  namespace :admin do
    resources :maps, :only => ['index', 'destroy'] do
      post 'make_primary', on: :member
      post 'unmake_primary', on: :member
      post 'recreate', on: :collection
    end
    resources :users, :only => ['index', 'destroy', 'show']
    resources :photos, :only => ['index', 'destroy', 'show'] do
      post 'make_tile', on: :member
      post 'unmake_tile', on: :member
      post 'publish', on: :member
      post 'unpublish', on: :member
      post 'cancel', on: :member
      get 'unpublished', on: :collection
      get 'cancelled', on: :collection
    end
    resources :regions, :only => ['index', 'show'] do
      resources :generics, :only => ['show', 'create', 'new', 'destroy']
      resources :photos, :only => ['index', 'show', 'destroy'], :controller => 'region_photos' do
        post 'make_tile', on: :member
        post 'unmake_tile', on: :member
        post 'publish', on: :member
        post 'unpublish', on: :member
        post 'cancel', on: :member
      end
    end
    resources :feedbacks, :only => ['index', 'show', 'destroy']
    resources :winners, only: ['index', 'new', 'create']
    resources :prizes, only: ['index', 'new', 'create']
    get "/search" => "dashboard#search"
    get "/" => "dashboard#index"
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook, :developer, :vkontakte]

  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update


  has_many :photos, :dependent => :destroy
  has_many :uploads, :dependent => :destroy
  has_many :identities, :dependent => :destroy

  # validates :first_name, presence: true
  # validates :last_name, presence: true
  # validates :post_index, presence: true
  # validates :city, presence: true
  # validates :street, presence: true
  # validates :street_number, presence: true
  # validates :apts_number, presence: true

  paginates_per 20

  acts_as_voter

  def name
    [first_name, last_name].join(' ')
  end

  def self.find_for_oauth(auth, signed_in_resource = nil)

    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          last_name: auth.info.last_name,
          first_name: auth.info.first_name,
          #username: auth.info.nickname || auth.uid,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,8]
        )
        user.save!
      end
    end

    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_action :authenticate_admin!

  layout "admin"

  def index
    @users = User.order('created_at DESC').page params[:page]
  end

  def show
    @user = User.includes(:photos).where(:id => params[:id]).first
  end

  def destroy

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:update, :finish_signup]

  def new
    if params[:message].present?
      @message = params[:message]
    end
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      sign_in(@user, :bypass => true)
      redirect_to new_photo_path
    else
      render :action => 'new'
    end
  end

  # PATCH/PUT /users/:id.:format
  def update
    # authorize! :update, @user
    respond_to do |format|
      if @user.update(user_params)
        sign_in(@user == current_user ? @user : current_user, :bypass => true)
        format.html { redirect_to @user, notice: 'Your profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET/PATCH /users/:id/finish_signup
  def finish_signup
    # authorize! :update, @user
    if request.patch? && params[:user] #&& params[:user][:email]
      if @user.update(user_params)
        sign_in(@user, :bypass => true)
        redirect_to new_photo_path
      else
        @show_errors = true
        render :finish_signup, :alert => @user.errors
      end
    end
  end

  # DELETE /users/:id.:format
  def destroy
    # authorize! :delete, @user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      accessible = [ :last_name, :first_name, :email ] # extend with your own params
      accessible << [ :password, :password_confirmation ] unless params[:user][:password].blank?
      params.require(:user).permit(accessible)
    end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/finish_signup.html.haml
= content_for :main do
  .small-1.columns.centered
    = link_to "О конкурсе", about_path
  .small-1.columns.centered
    = link_to "Карта счастья", map_path
  .small-1.columns.centered
    = link_to "Победители", winners_path
  .small-1.columns.centered
    = link_to "Правила", rules_path

= content_for :page_title do
  %title Регистрация | Карта счастья

#add-email.user-email-form
  .row.inpage-form
    .small-1.columns &nbsp;
    .small-4.columns
      %h1 <br><br>Завершение регистрации
      %p(style="font-size: 12px;") Укажите своей E-mail адрес для завершения регистрации
      = form_for(current_user, :as => 'user', :url => finish_signup_path(current_user), :html => { role: 'form'}) do |f|
        - if @user.errors.any?
          #error_explanation
            - @user.errors.full_messages.each do |msg|
              = msg
              %br/
        .line
          = f.text_field :email, :autofocus => true, :value => '', class: 'form-control input-lg', placeholder: 'Например: vasiliy@mail.ru'
        .actions
          = f.submit 'Отправить', :id => 'sign-up-submit'
    .row

:javascript
  $('body').on('click', '#sign-up-submit', function() {
    console.log('Registration finalized');
    ga('send', 'event', 'Registration', 'SecondStep', 'Sokolov', 1000);
  });

app/views/users/new.html.haml
= content_for :main do
  .small-1.columns.centered
    = link_to "О конкурсе", about_path
  .small-1.columns.centered
    = link_to "Карта счастья", map_path
  .small-1.columns.centered
    = link_to "Победители", winners_path
  .small-1.columns.centered
    = link_to "Правила", rules_path

= content_for :page_title do
  %title Регистрация | Карта счастья

#add-email
  .row.inpage-form
    .small-1.columns &nbsp;
    .small-4.columns
      %h1 <br><br>Регистрация
      - if @message.present?
        %p(style="font-size: 12px;")= @message
      - else
        %p(style="font-size: 12px;") Все поля обязательны для заполнения
      = form_for(@user, :as => :user, :url => create_user_path(@user), :html => { role: 'form'}, :data => {:abide => ''}) do |f|
        .row
          .small-3.columns.input-holder
            %input#last_name.last-name.e{:name => "user[last_name]", :placeholder => "Фамилия", :required => "", :type => "text"}
              %small.error Это обязательное поле
          .small-3.columns.input-holder
            %input#first_name.first-name.e{:name => "user[first_name]", :placeholder => "Имя", :required => "", :type => "text"}
              %small.error Это обязательное поле
        .row
          #email_holder.small-3.columns.input-holder
            %input#register_email.email.e{:name => "user[email]", :placeholder => "E-mail", :required => "", :type => "email"}
              %small.error Неправильный email или он уже зарегистрирован
          .small-3.columns.input-holder
            %span.rounded-help.has-tip{"aria-haspopup" => "true", "data-tooltip" => "", :title => "Введите ваш e-mail адрес"} ?
        .row
          .small-3.columns.input-holder
            %input#user_password.password.e{:name => "user[password]", :placeholder => "Пароль", :required => "", :type => "password"}
              %small.error Минимальная длина &mdash; 8 символов
          .small-3.columns.input-holder
            %input.password-confirm.e{"data-equalto" => "user_password", :name => "user[password_confirmation]", :placeholder => "Еще раз", :required => "", :type => "password"}
              %small.error Пароли должны совпадать
        .actions
          = f.submit 'Отправить'
    .row