config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { omniauth_callbacks: 'callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  match '/users/new' => 'users#new', via: [:get, :post], :as => 'new_user'
  post '/users/create' => 'users#create', :as => 'create_user'

  get '/users/auth/odnoklassniki/callback' => 'callbacks#odnoklassniki'

  devise_for :admins

  root 'front#index'
  get '/rules' => 'front#rules', :as => 'rules'
  get '/about' => 'front#about', :as => 'about'
  get '/winners' => 'front#winners', :as => 'winners'
  resources :photos, :only => [:create, :new, :show]
  resources :uploads, :only => [:create]
  get '/user/:id' => 'front#user', :as => 'user'
  get '/map(/:alias)' => 'front#map', :as => 'map'

  post '/api/check_email' => 'api#check_email'
  post '/api/create_user' => 'api#create_user'
  post '/api/login_user' => 'api#login_user'
  post '/api/get_points' => 'api#get_points'
  post '/api/get_points_paged' => 'api#get_points_paged'
  post '/api/get_user_points' => 'api#get_user_points'
  post '/api/get_point' => 'api#get_point'
  post '/api/upvote' => 'api#upvote'
  post '/api/load_more_winners' => 'api#load_more_winners'
  post '/api/feedback' => 'api#feedback'

  %w( 404 422 500 ).each do |code|
    get code, :to => 'errors#show', :code => code
  end

  namespace :admin do
    resources :maps, :only => ['index', 'destroy'] do
      post 'make_primary', on: :member
      post 'unmake_primary', on: :member
      post 'recreate', on: :collection
    end
    resources :users, :only => ['index', 'destroy', 'show']
    resources :photos, :only => ['index', 'destroy', 'show'] do
      post 'make_tile', on: :member
      post 'unmake_tile', on: :member
      post 'publish', on: :member
      post 'unpublish', on: :member
      post 'cancel', on: :member
      get 'unpublished', on: :collection
      get 'cancelled', on: :collection
    end
    resources :regions, :only => ['index', 'show'] do
      resources :generics, :only => ['show', 'create', 'new', 'destroy']
      resources :photos, :only => ['index', 'show', 'destroy'], :controller => 'region_photos' do
        post 'make_tile', on: :member
        post 'unmake_tile', on: :member
        post 'publish', on: :member
        post 'unpublish', on: :member
        post 'cancel', on: :member
      end
    end
    resources :feedbacks, :only => ['index', 'show', 'destroy']
    resources :winners, only: ['index', 'new', 'create']
    resources :prizes, only: ['index', 'new', 'create']
    get "/search" => "dashboard#search"
    get "/" => "dashboard#index"
  end

end

app/controllers/admin/region_photos_controller.rb
class Admin::RegionPhotosController < ApplicationController

  before_action :authenticate_admin!

  layout "admin"

  def index
    @region = Region.find(params[:region_id])
    if params[:sort] == 'popular'
      @photos = Photo.where(:region_id => @region.id).order('created_at DESC').page params[:page]
    else
      @photos = Photo.where(:region_id => @region.id).order('cached_votes_up DESC, created_at DESC').page params[:page]
    end
  end

  def show
    @region = Region.find(params[:region_id])
    @photo = Photo.includes([:user, :region]).where(:id => params[:id]).first
  end

  def publish
    @region = Region.find(params[:region_id])
    @photo = Photo.includes(:user).find(params[:id])
    @photo.is_approved = true
    @photo.save
    UserMailer.approved_email(@photo).deliver_now
    flash[:notice] = 'Фото опубликовано'
    redirect_to :back
  end

  def cancel
    @region = Region.find(params[:region_id])
    @photo = Photo.includes(:user).find(params[:id])
    @photo.is_cancelled = true
    @photo.save
    UserMailer.cancelled_email(@photo).deliver_now
    flash[:notice] = 'Фото отменено'
    redirect_to :back
  end

  def unpublish
    @region = Region.find(params[:region_id])
    @photo = Photo.find(params[:id])
    @photo.is_approved = false
    @photo.save
    flash[:notice] = 'Фото снято с публикации'
    redirect_to :back
  end

  def make_tile
    @region = Region.find(params[:region_id])
    Photo.where(:region_id => @region.id).where(:is_tile => true).each do |photo|
      photo.update_attribute(:is_tile, false)
    end
    @photo = Photo.find(params[:id])
    @photo.is_tile = true
    @photo.save
    flash[:notice] = 'Фото сделано тайлом для своего региона'
    redirect_to :back
  end

  def unmake_tile
    @region = Region.find(params[:region_id])
    @photo = Photo.find(params[:id])
    @photo.is_tile = false
    @photo.save
    flash[:notice] = 'Фото убрано из тайлов'
    redirect_to :back
  end

end

app/helpers/admin/region_photos_helper.rb
module Admin::RegionPhotosHelper
end

app/views/admin/region_photos/index.html.haml
- content_for :header do

  .pull-right
    = link_to admin_regions_path, :class => 'button button-hollow button-round button-small preview-website' do
      Вернуться к списку

    = link_to admin_region_photos_path(:region_id => @region.id, :sort => 'newest'), :class => 'button button-hollow button-round button-small preview-website' do
      Список фотографий

  .breadcrumbs
    Фотографии в регионе:<br>
    = @region.title



  - if Region.has_tile(@region).exists?

    .bordered-tile

      %h4 Фото для карты:

      .map-block
        - @tile = Photo.where(:region_id => @region.id).where(:is_tile => true).first
        = image_tag @tile.tile_url



  %nav.tabs
    %ul
      - if params[:sort] == 'popular'
        %li
          = link_to "Свежие", admin_region_photos_path(:region_id => @region.id, :sort => 'newest')
        %li.active
          = link_to "Популярные", admin_region_photos_path(:region_id => @region.id, :sort => 'popular')
      - else
        %li.active
          = link_to "Свежие", admin_region_photos_path(:region_id => @region.id, :sort => 'newest')
        %li
          = link_to "Популярные", admin_region_photos_path(:region_id => @region.id, :sort => 'popular')

.table-container


  %table.table
    %thead
      %tr
        %th(style="width: 30px")
        %th
          Название
        %th(style="width: 200px; text-align: center") Пользователь
        %th(style="width: 100px; text-align: right")

    - @photos.each do |photo|
      - if photo.is_approved
        %tr
          %td
            .image-tiny
              = link_to photo.image_url, :class => 'fancybox' do
                = image_tag photo.image_url(:tiny)
          %td
            = link_to admin_region_photo_path(@region.id, photo.id) do
              = photo.title
          %td(style="text-align:left")
            = link_to (photo.user.first_name + '&nbsp;' + photo.user.last_name).html_safe, admin_user_path(photo.user.id)
          %td(style="text-align:center")
            - if !photo.is_tile
              = link_to make_tile_admin_region_photo_path(@region.id, photo.id), :method => "post", :title => 'Добавить на карту' do
                %span.icon.icon-plus
            - else
              %span.icon.icon-min

      - else
        %tr.unapproved
          %td
            .image-tiny
              = image_tag photo.image_url(:tiny)
          %td
            = link_to admin_region_photo_path(@region.id, photo.id) do
              = photo.title
          %td(style="text-align:left")
            = link_to (photo.user.first_name + '&nbsp;' + photo.user.last_name).html_safe, admin_user_path(photo.user.id)
          %td(style="text-align:center")
            - if !photo.is_tile
              = link_to make_tile_admin_region_photo_path(@region.id, photo.id), :method => "post", :title => 'Добавить на карту' do
                %span.icon.icon-plus
            - else
              %span.icon.icon-min

  .pages-container
    = paginate @photos

app/views/admin/region_photos/show.html.haml
- content_for :header do

  .pull-right
    = link_to admin_region_photos_path(@region.id), :class => 'button button-hollow button-round button-small preview-website' do
      Вернуться к списку

  .breadcrumbs
    = @photo.title

.table-container

  %table.table.user-table
    %tr
      %th(style="text-align:right; width: 200px") Заголовок
      %td= @photo.title
    %tr
      %th(style="text-align:right; width: 200px") Автор
      %td= @photo.user.first_name + ' ' + @photo.user.last_name
    %tr
      %th(style="text-align:right; width: 200px") Регион
      %td= @photo.region.title
    %tr
      %th(style="text-align:right; width: 200px") Положение
      %td
        = @photo.lat.to_s + ';' + @photo.lng.to_s
    %tr
      %th(style="text-align:right; width: 200px") Голосов
      %td
        = @photo.votes_for.size

.container
  .tile-help
    %p
      - if @photo.is_approved
        = link_to "Снять с публикации", unpublish_admin_photo_path(@photo.id), :method => :post, :class => 'button button-primary'
      - else
        = link_to "Опубликовать", publish_admin_photo_path(@photo.id), :method => :post, :class => 'button button-primary'


.table-container

  .image-mapper
    .image
      = image_tag @photo.image_url
    .mapper
      .mapbox#mapbox(style="height: 360px")
      = image_tag @photo.tile_url, :class => 'tile'


:javascript
  ymaps.ready(init);

  function init () {
    var myMap = new ymaps.Map("mapbox", {
      center: [#{@photo.lat}, #{@photo.lng}],
      zoom: #{@photo.zoom},
      controls: ['smallMapDefaultSet']
    });

    var myPlacemark = new ymaps.Placemark([#{@photo.lat}, #{@photo.lng}], {}, {
      iconLayout: "default#image",
      iconImageHref: "#{@photo.image_url(:marker)}",
      iconImageSize: [40, 45],
      iconImageOffset: [-20, -45]
    });

    myMap.geoObjects.add(myPlacemark);

  }