config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { omniauth_callbacks: 'callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  match '/users/new' => 'users#new', via: [:get, :post], :as => 'new_user'
  post '/users/create' => 'users#create', :as => 'create_user'

  get '/users/auth/odnoklassniki/callback' => 'callbacks#odnoklassniki'

  devise_for :admins

  root 'front#index'
  get '/rules' => 'front#rules', :as => 'rules'
  get '/about' => 'front#about', :as => 'about'
  get '/winners' => 'front#winners', :as => 'winners'
  resources :photos, :only => [:create, :new, :show]
  resources :uploads, :only => [:create]
  get '/user/:id' => 'front#user', :as => 'user'
  get '/map(/:alias)' => 'front#map', :as => 'map'

  post '/api/check_email' => 'api#check_email'
  post '/api/create_user' => 'api#create_user'
  post '/api/login_user' => 'api#login_user'
  post '/api/get_points' => 'api#get_points'
  post '/api/get_points_paged' => 'api#get_points_paged'
  post '/api/get_user_points' => 'api#get_user_points'
  post '/api/get_point' => 'api#get_point'
  post '/api/upvote' => 'api#upvote'
  post '/api/load_more_winners' => 'api#load_more_winners'
  post '/api/feedback' => 'api#feedback'

  %w( 404 422 500 ).each do |code|
    get code, :to => 'errors#show', :code => code
  end

  namespace :admin do
    resources :maps, :only => ['index', 'destroy'] do
      post 'make_primary', on: :member
      post 'unmake_primary', on: :member
      post 'recreate', on: :collection
    end
    resources :users, :only => ['index', 'destroy', 'show']
    resources :photos, :only => ['index', 'destroy', 'show'] do
      post 'make_tile', on: :member
      post 'unmake_tile', on: :member
      post 'publish', on: :member
      post 'unpublish', on: :member
      post 'cancel', on: :member
      get 'unpublished', on: :collection
      get 'cancelled', on: :collection
    end
    resources :regions, :only => ['index', 'show'] do
      resources :generics, :only => ['show', 'create', 'new', 'destroy']
      resources :photos, :only => ['index', 'show', 'destroy'], :controller => 'region_photos' do
        post 'make_tile', on: :member
        post 'unmake_tile', on: :member
        post 'publish', on: :member
        post 'unpublish', on: :member
        post 'cancel', on: :member
      end
    end
    resources :feedbacks, :only => ['index', 'show', 'destroy']
    resources :winners, only: ['index', 'new', 'create']
    resources :prizes, only: ['index', 'new', 'create']
    get "/search" => "dashboard#search"
    get "/" => "dashboard#index"
  end

end

app/models/region.rb
class Region < ActiveRecord::Base

  has_many :photos
  has_many :generics

  scope :has_tile, lambda { |region|
    joins(:photos).where('regions.id = ?', region.id).where('photos.is_tile = ?', true)
  }

  scope :has_generics, lambda { |region|
    joins(:generics).where('regions.id = ?', region.id).where('generics.region_id = ?', region.id)
  }

  def self.getYandexNames
    Region.all.each do |region|
      query = URI::escape('Россия, '+region.title)
      response = HTTParty.get('http://geocode-maps.yandex.ru/1.x/?geocode='+query+'&format=json&lang=ru_RU')
      body = JSON.parse(response.body)
      if body["response"]["GeoObjectCollection"]["featureMember"][0]["GeoObject"]["metaDataProperty"]["GeocoderMetaData"]["AddressDetails"]["Country"]["CountryNameCode"].present? && body["response"]["GeoObjectCollection"]["featureMember"][0]["GeoObject"]["metaDataProperty"]["GeocoderMetaData"]["AddressDetails"]["Country"]["CountryNameCode"] == "RU"
        region.lat = body["response"]["GeoObjectCollection"]["featureMember"][0]["GeoObject"]["Point"]["pos"].split(' ')[0]
        region.lng = body["response"]["GeoObjectCollection"]["featureMember"][0]["GeoObject"]["Point"]["pos"].split(' ')[1]
        region.title = body["response"]["GeoObjectCollection"]["featureMember"][0]["GeoObject"]["metaDataProperty"]["GeocoderMetaData"]["AddressDetails"]["Country"]["AddressLine"]
        region.alias_path = Russian.translit(region.title).parameterize
        region.save
        p region.title
      end

      sleep(1)

       #

      # # $.get 'http://geocode-maps.yandex.ru/1.x/?geocode='+input.val().replace(' ','+')+'&format=json&results=1&ll='+self.search_point[1]+','+self.search_point[0]+'&spn=1.552069,1.400552&rspn=0&lang=ru_RU', (data) ->
      #             button.html('Найти')
      #             if data.response.GeoObjectCollection.featureMember[0].GeoObject.Point
      #               coords = data.response.GeoObjectCollection.featureMember[0].GeoObject.Point.pos.split(' ')
      #               if coords.length == 2
      #                 map.setCenter([coords[1], coords[0]],11)
      #
      #
      # result = Geokit::Geocoders::YandexGeocoder.geocode('Россия, '+region.title)
      # p result.to_yaml
      # if result.country_code == 'RU'
      #   region.lat = result.lat
      #   region.lng = result.lng
      #   region.title = result.street_address
      #   region.alias_path = Russian.translit(result.street_address).parameterize
      #   region.save
      #   p region.title
      #   sleep(3)
      # end
    end
  end

end

app/controllers/admin/regions_controller.rb
class Admin::RegionsController < ApplicationController

  before_action :authenticate_admin!
  layout "admin"

  def index
    @regions = Region.order('title ASC').all
  end

  def show
    @region = Region.find(params[:id])
    @generics = Generic.where(:region_id => @region.id)
    @photos = Photo.where(:region_id => @region.id).order('created_at DESC').page params[:page]
  end

end

app/helpers/admin/regions_helper.rb
module Admin::RegionsHelper
end

app/views/admin/regions/index.html.haml
- content_for :header do

  .breadcrumbs
    Регионы

  %p Для создания карты необходимо чтобы у каждого региона был выбран тайл или была загружена хотя бы одна заглушка

.table-container


  %table.table
    %thead
      %tr
        %th
          Название
        %th(style="width: 40px; text-align: center") Заглушки
        %th(style="width: 40px; text-align: center")
        %th(style="width: 50px; text-align: right") Фотографий

    - @regions.each do |region|
      - if Region.has_tile(region).exists?
        %tr.tiled
          %td
            = link_to admin_region_path(region.id) do
              = region.title
          %td
            = Region.has_generics(region).size
          %td
            Тайл&nbsp;выбран
          %td(style="text-align:right")
            = region.photos.size
      - else
        - if !Region.has_generics(region).exists?
          %tr.untiled
            %td
              = link_to admin_region_path(region.id) do
                = region.title
            %td
              = Region.has_generics(region).size
            %td
              Тайл&nbsp;не&nbsp;выбран
            %td(style="text-align:right")
              = region.photos.size
        - else
          %tr.tiled
            %td
              = link_to admin_region_path(region.id) do
                = region.title
            %td
              = Region.has_generics(region).size
            %td
              Тайл&nbsp;не&nbsp;выбран
            %td(style="text-align:right")
              = region.photos.size

app/views/admin/regions/show.html.haml
- content_for :header do

  .pull-right
    = link_to admin_regions_path, :class => 'button button-hollow button-round button-small preview-website' do
      Вернуться к списку

    = link_to admin_region_photos_path(:region_id => @region.id, :sort => 'newest'), :class => 'button button-hollow button-round button-small preview-website' do
      Список фотографий

  .breadcrumbs
    = @region.title

.table-container

  %table.table.user-table
    %tr
      %th(style="text-align:right; width: 200px") Название
      %td= @region.title
    %tr
      %th(style="text-align:right; width: 200px") Широта
      %td= @region.lat.to_s
    %tr
      %th(style="text-align:right; width: 200px") Долгота
      %td= @region.lng.to_s
    %tr
      %th(style="text-align:right; width: 200px") Фотографии
      %td= @region.photos.size

.container.clearfix.cf
  %br
  %br
  .pull-right
    = link_to new_admin_region_generic_path(@region.id), :class => 'button button-hollow button-round button-small preview-website' do
      Новая заглушка

  %h3
    Картинки-заглушки
    %small(style="color: #ccc")= @generics.size


  %p Эти картинки используются если не в регионе не выбрана картинка для карты

  - if @generics.any?
    .photos-block
      - @generics.each do |photo|
        .photo
          .image
            %a.fancybox{:href => photo.tile_url}
              = image_tag photo.tile_url
          .description
            = link_to "Удалить", admin_region_generic_path(@region.id, photo.id), :method => 'delete'

    .pages-container
      = paginate @photos

  - else
    %p Пока не загружено